$$ &&
	$$('sia', {
		xprefix: 'https://xaidozy.github.io/sia',
		data: [
			'o^Ya_Soshla_S_Uma;T.A.T.u',
			'a^Foreign_Friends',
			'japan1;KOKIA;y^ありがとう',
			'a^Ngau_Hung;Hoaprox',
			'Guitar_Type;ET Soul',
			'o^Alleyways;NightCore',
			'Yo^Star_Track;NightCore',
			'p^Bgm_A_MC_Server',
			'go^Deep_Blue;William Black',
			'SUECO',
			'Duvet;Boa',
			'Duvet_Pure;Boa;Duvet(纯)',
			'p^Miraie',
			'Save_Me',
			'Leaving_Home;Park Bird',
			'a^Experiment_626;WORKER',
			'Now_Or_Never;a^Valentin',
			'a^Bgm_Dungeon',
			'g^Bgm_Fast_Sky',
			'Cdong4dong4;久保ユリカ&水瀬いのり;y^動く、動く',
			'a^SO_TIRED;Avery',
			'Czang4_Pure;Cover:18;a^葬(纯)',
			'Cxin1pai1shu4;Hodge;心拍数(口琴)',
			'Bgm_Cchou1jiang3xi4tong3;;Bgm 抽奖系统',
			'a^WISH_Melodic_Deep_House',
			'R^Q',
			'go^diaryplugg',
			'R^N',
			'R^R',
			'i_watch_the_moon;tek it;p^i watch the moon(Cafuné)',
			'R^O',
			'ru^Run_55;Manu Zain',
			'po^Low_R',
			'R^G',
			'au^Love_in_561.3mb',
			'Wreck_it;g^Pixar;Wreck it(Ralph)',
			'g^Key_Fm;Ray x RD',
			'g^Would_U_Remember_Me;go missing',
			'g^Chill',
			'Neverender;Bokoven',
			'Y^Niamora',
			'R^Hapaya0a33',
			'P^Jazz_HipHop;p^Zy-Dance',
			'P^Dag_Tilbage;Nik Jay',
			'a^Anime_x_Pluggnb_x_YuKI',
			'ao^lilac',
			'g^Melody;ZIV/KIPES',
			'R^E',
			'R^B',
			'R^F',
		],
	});
