$$ &&
	$$('sia', {
		xprefix: 'https://xaidozy.github.io/sia',
		data: [
			'Ya_Soshla_S_Uma;T.A.T.u;y',
			'Foreign_Friends;;a',
			'japan1;KOKIA;y;ありがとう',
			'Ngau_Hung;Hoaprox;a',
			'Guitar_Type;ET Soul',
			'Alleyways;NightCore;a',
			'Star_Track;NightCore',
			'Bgm_A_MC_Server;;p',
			'Deep_Blue;William Black;a',
			'SUECO',
			'Duvet;Boa;y',
			'Duvet_Pure;Boa;p;Duvet(纯)',
			'Miraie;;p',
			'Save_Me;;r',
			'Leaving_Home;Park Bird;p',
			'Experiment_626;WORKER;a',
			'Now_Or_Never;a^Valentin;p',
			'Bgm_Dungeon;;a',
			'Bgm_Fast_Sky;;y',
			'Cdong4dong4;久保ユリカ&水瀬いのり;y;#動く、動く',
			'SO_TIRED;Avery;a',
			'Czang4_Pure;Cover:18;a;葬(纯)',
			'Cxin1pai1shu4;Hodge;p;心拍数(口琴)',
			'Bgm_Cchou1jiang3xi4tong3;;p;Bgm 抽奖系统',
			'WISH_Melodic_Deep_House;;a',
			'Q;;r',
			'diaryplugg',
			'N;;r',
			'R;;r',
			'i_watch_the_moon;tek it;p;i watch the moon(Cafuné)',
			'O;;r',
			'Run_55;Manu Zain;ru',
			'Low_R;;p',
			'G;;r',
			'Love_in_561.3mb;;y',
			'Wreck_it;;Pixar;Wreck it(Ralph)',
			'Key_Fm;Ray x RD;a',
			'Would_U_Remember_Me;go missing',
			'Chill;;a',
			'Neverender;Bokoven;y',
			'Niamora;;Y',
			'Hapaya0a33;;r',
			'Jazz_HipHop;Zy-Dance;p',
			'cloudbxy_x_vlm_x_epv;;a',
			'Anime_x_Pluggnb_x_YuKI;;a',
			'lilwaifu_x_lilac_x_lb66;;a',
			'Melody;ZIV/KIPES',
			'E;;r',
			'B;;r',
			'F;;r',
		],
	});
